- hosts: localhost
  connection: local
  vars:
    app_environment: "dev"
    stack_name: "scisupplier_bra_48"
    config_dir: "~/git_repos/TechOps/config/stacks"
    deploy_service: "scisupplier_fs_gateway"
    start_time: 1656
    output_dir: "/Magellan/Export/BuyerRemittanceAdvice-rerun"
    build: ci-34_7.2.3
    send_mail_enabled: true
    scheduled_cron_expression: "0 00 10 * * *"
    service_time: "0721"
  
  tasks:

  - name: Run Curl
    command: 'curl -D - -X "POST" -H "Accept: application/json" -H "Content-Type: application/json" -H "X-Rundeck-Auth-Token: hV9YrFJsvNSDJDOkc9JQ8qBfqsxtXzUr" -d "{\"argString\":\"-build ci-13_7.2.2 -output_dir /Magellan/Export/BuyerRemittanceAdvice48 -start_time 1651 -app_environment dev -stack_name scisupplier_bra_48 \"}" "https://rundeck.awsswarm.primerev.com/api/16/job/8407b6d8-1f78-4fcb-ac5f-3871a93df343/executions"'
