version: 2
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: mullnerz/ansible-playbook # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - setup_remote_docker:
          version: 18.05.0-ce
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run: |
         # create a dummy container which will hold a volume with config
         docker create -v /ansible/playbooks --name configs alpine:3.4 /bin/true
         # copy a config file into this volume
         docker cp ~/project/ansible/. configs:/ansible/playbooks
         # start an application container using this volume
#         docker run --volumes-from configs mullnerz/ansible-playbook

      - run: docker run --volumes-from configs --name chris -it mullnerz/ansible-playbook ansible-playbook compose-creator.yml

      - run:
          command: |
            mkdir -p /tmp/compose_files

      - run: docker exec -it chris ls ~/git_repos/TechOps/config/stacks/scisupplier_issuing-switch/dev


      - store_artifacts:
          path: /tmp/compose_file
